---
title: "Lock-free sweeps"

filters:
- diagram

format:
  revealjs: 
    slide-number: true
    chalkboard: 
      buttons: false
    preview-links: auto
    theme: moon
    logo: images/fluxim.png
    css: styles.css

diagram:
  engine:
    tikz:
      header-includes: |
          \usetikzlibrary{shapes.geometric, arrows, backgrounds, positioning, quotes}

resources:
  - demo.pdf
---

## Implementation - overview

``` tikz
\scalebox{1.5}{
\definecolor{cosmiclatte}{HTML}{FFF8E7}
\begin{tikzpicture}[background rectangle/.style={fill=cosmiclatte}, show background rectangle]
\tikzstyle{simple} = [rectangle, rounded corners, minimum width=3cm, minimum height=1cm,text centered, draw=black, fill=yellow!70]
\tikzstyle{arrow} = [thick,->,>=stealth, draw=black]
\node (TaskOrchestrator) [simple] {\begin{tabular}{c} \texttt{TaskOrchestrator} \\ \textbullet\ Handles graph \\ \textbullet\ runs tasks \end{tabular}};
\node (AbstractTask) [simple, right of=TaskOrchestrator, xshift=5cm] {\begin{tabular}{c} \texttt{AbstractTask} \\ \textbullet\ Manages properties \\ \textbullet\ runs payload \end{tabular}};
\node (Sweeper) [simple, right of=AbstractTask, xshift=5cm] {\begin{tabular}{c} \texttt{Sweeper} \\ \textbullet\ Creates abstract graph\end{tabular}};
\node (TaskResult) [simple, below of=AbstractTask, yshift=-2.5cm] {\begin{tabular}{c} \texttt{AbstractTaskResult} \\ \textbullet\ Represents coupling\end{tabular}};


\draw [arrow] (TaskOrchestrator) -- (AbstractTask);
\draw [arrow] (Sweeper) -- (AbstractTask);
\draw [arrow] (AbstractTask) -- (TaskResult);
\end{tikzpicture}
}
```

## Task Orchestrator - Abstract graph

``` tikz
\definecolor{cosmiclatte}{HTML}{FFF8E7}
\begin{tikzpicture}[background rectangle/.style={fill=cosmiclatte}, show background rectangle]
\tikzstyle{simple} = [rectangle, rounded corners, minimum width=3cm, minimum height=1cm,text centered, draw=black, fill=yellow!70]
\tikzstyle{arrow} = [thick,->,>=stealth, draw=black]
\node (Scattering) [simple] {Scattering};
\node (Fresnel) [simple, right of=Scattering, xshift=3cm] {Fresnel};
\node (NetRadiation) [simple, below of=Scattering, yshift=-2.5cm, xshift=1.5cm] {NetRadiation};
\node (ScatteringPP) [simple, below of=NetRadiation, yshift=-2.5cm] {Scattering PP};

\draw [arrow] (Scattering) -- (NetRadiation);
\draw [arrow] (Fresnel) -- (NetRadiation);
\draw [arrow] (NetRadiation) -- (ScatteringPP);
\end{tikzpicture}
```

## Task Orchestrator - Instantiation

``` tikz
\definecolor{cosmiclatte}{HTML}{FFF8E7}
\begin{tikzpicture}[background rectangle/.style={fill=cosmiclatte}, show background rectangle]
\tikzstyle{simple} = [rectangle, rounded corners, minimum width=3cm, minimum height=1cm,text centered, draw=black, fill=yellow!70]
\tikzstyle{arrow} = [thick,->,>=stealth, draw=black]
\node (scata) [simple] {Scattering A};
\node (scatb) [simple, right of=scata, xshift=3cm] {Scattering B};
\node (fresnel1) [simple, right of=scatb, xshift=3cm] {Fresnel 1};
\node (fresnel2) [simple, right of=fresnel1, xshift=3cm] {Fresnel 2};

\node (NetRadiation) [simple, below of=scatb, yshift=-2.5cm, xshift=1.5cm] {NetRadiation};
\node (ScatteringPP) [simple, below of=NetRadiation, yshift=-2.5cm] {Scattering PP};

\draw [arrow] (scata) -- (NetRadiation);
\draw [arrow] (scatb) -- (NetRadiation);
\draw [arrow] (fresnel1) -- (NetRadiation);
\draw [arrow] (fresnel2) -- (NetRadiation);
\draw [arrow] (NetRadiation) -- (ScatteringPP);
\end{tikzpicture}
```

## Task Orchestrator - Instantiation

``` tikz
\definecolor{cosmiclatte}{HTML}{FFF8E7}
\begin{tikzpicture}[background rectangle/.style={fill=cosmiclatte}, show background rectangle]
\tikzstyle{simple} = [rectangle, rounded corners, minimum width=3cm, minimum height=1cm,text centered, draw=black, fill=yellow!70]
\tikzstyle{arrow} = [thick,->,>=stealth, draw=black]
\node (scata) [simple] {Scattering A};
\node (scatb) [simple, right of=scata, xshift=3cm] {Scattering B};
\node (fresnel1) [simple, right of=scatb, xshift=3cm] {Fresnel 1};
\node (fresnel2) [simple, right of=fresnel1, xshift=3cm] {Fresnel 2};

\node (netrada1) [simple, below of=scata, yshift=-1.5cm] {\begin{tabular}{c} Net Rad A1 \\ \texttt{incoming:2} \end{tabular}};
\node (netrada2) [simple, below of=scatb, yshift=-1.5cm] {\begin{tabular}{c} Net Rad A2 \\ \texttt{incoming:2} \end{tabular}};
\node (netradb1) [simple, below of=fresnel1, yshift=-1.5cm] {\begin{tabular}{c} Net Rad B1 \\ \texttt{incoming:2} \end{tabular}};
\node (netradb2) [simple, below of=fresnel2, yshift=-1.5cm] {\begin{tabular}{c} Net Rad B2 \\ \texttt{incoming:2} \end{tabular}};

\node (ScatteringPP) [simple, below of=netrada2, yshift=-2.5cm, xshift=1.5cm] {Scattering PP};

\draw [arrow] (scata) -- (netrada1);
\draw [arrow] (scata) -- (netrada2);
\draw [arrow] (scatb) -- (netradb1);
\draw [arrow] (scatb) -- (netradb2);
\draw [arrow] (fresnel1) -- (netrada1);
\draw [arrow] (fresnel1) -- (netradb1);
\draw [arrow] (fresnel2) -- (netrada2);
\draw [arrow] (fresnel2) -- (netradb2);

\draw [arrow] (netrada1) -- (ScatteringPP);
\draw [arrow] (netrada2) -- (ScatteringPP);
\draw [arrow] (netradb1) -- (ScatteringPP);
\draw [arrow] (netradb2) -- (ScatteringPP);
\end{tikzpicture}
```

## Task Orchestrator - Instantiation

``` tikz
\definecolor{cosmiclatte}{HTML}{FFF8E7}
\begin{tikzpicture}[background rectangle/.style={fill=cosmiclatte}, show background rectangle]
\tikzstyle{simple} = [rectangle, rounded corners, minimum width=3cm, minimum height=1cm,text centered, draw=black, fill=yellow!70]
\tikzstyle{arrow} = [thick,->,>=stealth, draw=black]
\node (scata) [simple] {Scattering A};
\node (scatb) [simple, right of=scata, xshift=3cm] {Scattering B};
\node (fresnel1) [simple, right of=scatb, xshift=3cm] {Fresnel 1};
\node (fresnel2) [simple, right of=fresnel1, xshift=3cm] {Fresnel 2};

\node (netrada1) [simple, below of=scata, yshift=-1.5cm] {Net Rad A1};
\node (netrada2) [simple, below of=scatb, yshift=-1.5cm] {Net Rad A2};
\node (netradb1) [simple, below of=fresnel1, yshift=-1.5cm] {Net Rad B1};
\node (netradb2) [simple, below of=fresnel2, yshift=-1.5cm] {Net Rad B2};

\node (scatppa1b1) [simple, below of=netrada1, yshift=-1.5cm, xshift=2cm] {Scattering PP A1B1};
\node (scatppa2b2) [simple, below of=netradb1, yshift=-1.5cm, xshift=2cm] {Scattering PP A2B2};


\draw [arrow] (scata) -- (netrada1);
\draw [arrow] (scata) -- (netrada2);
\draw [arrow] (scatb) -- (netradb1);
\draw [arrow] (scatb) -- (netradb2);
\draw [arrow] (fresnel1) -- (netrada1);
\draw [arrow] (fresnel1) -- (netradb1);
\draw [arrow] (fresnel2) -- (netrada2);
\draw [arrow] (fresnel2) -- (netradb2);

\draw [arrow] (netrada1) -- (scatppa1b1);
\draw [arrow] (netradb1) -- (scatppa1b1);
\draw [arrow] (netrada2) -- (scatppa2b2);
\draw [arrow] (netradb2) -- (scatppa2b2);
\end{tikzpicture}
```

Scattering post-processing collects over angle results!

## Wavefront pattern

``` tikz
\definecolor{cosmiclatte}{HTML}{FFF8E7}
\begin{tikzpicture}[background rectangle/.style={fill=cosmiclatte}, show background rectangle]
\tikzstyle{queue} = [rectangle, rounded corners, minimum width=3cm, minimum height=1cm,text centered, draw=black, fill=yellow!70]
\tikzstyle{run} = [rectangle, rounded corners, minimum width=3cm, minimum height=1cm,text centered, draw=black, fill=red!70]
\tikzstyle{finished} = [rectangle, rounded corners, minimum width=3cm, minimum height=1cm,text centered, draw=black, fill=green!70]
\tikzstyle{arrow} = [thick,->,>=stealth, draw=black]

\node (scata) [queue] {Scattering A};
\node (scatb) [queue, right of=scata, xshift=3cm] {Scattering B};
\node (fresnel1) [queue, right of=scatb, xshift=3cm] {Fresnel 1};
\node (fresnel2) [queue, right of=fresnel1, xshift=3cm] {Fresnel 2};

\node (netrada1) [queue, below of=scata, yshift=-1.5cm] {\begin{tabular}{c} Net Rad A1 \\ \texttt{incoming:2} \end{tabular}};
\node (netrada2) [queue, below of=scatb, yshift=-1.5cm] {\begin{tabular}{c} Net Rad A2 \\ \texttt{incoming:2} \end{tabular}};
\node (netradb1) [queue, below of=fresnel1, yshift=-1.5cm] {\begin{tabular}{c} Net Rad B1 \\ \texttt{incoming:2} \end{tabular}};
\node (netradb2) [queue, below of=fresnel2, yshift=-1.5cm] {\begin{tabular}{c} Net Rad B2 \\ \texttt{incoming:2} \end{tabular}};

\draw [arrow] (scata) -- (netrada1);
\draw [arrow] (scata) -- (netrada2);
\draw [arrow] (scatb) -- (netradb1);
\draw [arrow] (scatb) -- (netradb2);
\draw [arrow] (fresnel1) -- (netrada1);
\draw [arrow] (fresnel1) -- (netradb1);
\draw [arrow] (fresnel2) -- (netrada2);
\draw [arrow] (fresnel2) -- (netradb2);

\node (scatppa1b1) [queue, below of=netrada1, yshift=-1.5cm, xshift=2cm] {\begin{tabular}{c} Scattering PP A1B1 \\ \texttt{incoming:2} \end{tabular}};
\node (scatppa2b2) [queue, below of=netradb1, yshift=-1.5cm, xshift=2cm] {\begin{tabular}{c} Scattering PP A2B2 \\ \texttt{incoming:2} \end{tabular}};

\draw [arrow] (netrada1) -- (scatppa1b1);
\draw [arrow] (netradb1) -- (scatppa1b1);
\draw [arrow] (netrada2) -- (scatppa2b2);
\draw [arrow] (netradb2) -- (scatppa2b2);

\end{tikzpicture}
```

## Wavefront pattern

``` tikz
\definecolor{cosmiclatte}{HTML}{FFF8E7}
\begin{tikzpicture}[background rectangle/.style={fill=cosmiclatte}, show background rectangle]
\tikzstyle{queue} = [rectangle, rounded corners, minimum width=3cm, minimum height=1cm,text centered, draw=black, fill=yellow!70]
\tikzstyle{run} = [rectangle, rounded corners, minimum width=3cm, minimum height=1cm,text centered, draw=black, fill=red!70]
\tikzstyle{finished} = [rectangle, rounded corners, minimum width=3cm, minimum height=1cm,text centered, draw=black, fill=green!70]
\tikzstyle{arrow} = [thick,->,>=stealth, draw=black]

\node (scata) [run] {Scattering A};
\node (scatb) [run, right of=scata, xshift=3cm] {Scattering B};
\node (fresnel1) [run, right of=scatb, xshift=3cm] {Fresnel 1};
\node (fresnel2) [run, right of=fresnel1, xshift=3cm] {Fresnel 2};

\node (netrada1) [queue, below of=scata, yshift=-1.5cm] {\begin{tabular}{c} Net Rad A1 \\ \texttt{incoming:2} \end{tabular}};
\node (netrada2) [queue, below of=scatb, yshift=-1.5cm] {\begin{tabular}{c} Net Rad A2 \\ \texttt{incoming:2} \end{tabular}};
\node (netradb1) [queue, below of=fresnel1, yshift=-1.5cm] {\begin{tabular}{c} Net Rad B1 \\ \texttt{incoming:2} \end{tabular}};
\node (netradb2) [queue, below of=fresnel2, yshift=-1.5cm] {\begin{tabular}{c} Net Rad B2 \\ \texttt{incoming:2} \end{tabular}};

\draw [arrow] (scata) -- (netrada1);
\draw [arrow] (scata) -- (netrada2);
\draw [arrow] (scatb) -- (netradb1);
\draw [arrow] (scatb) -- (netradb2);
\draw [arrow] (fresnel1) -- (netrada1);
\draw [arrow] (fresnel1) -- (netradb1);
\draw [arrow] (fresnel2) -- (netrada2);
\draw [arrow] (fresnel2) -- (netradb2);

\node (scatppa1b1) [queue, below of=netrada1, yshift=-1.5cm, xshift=2cm] {\begin{tabular}{c} Scattering PP A1B1 \\ \texttt{incoming:2} \end{tabular}};
\node (scatppa2b2) [queue, below of=netradb1, yshift=-1.5cm, xshift=2cm] {\begin{tabular}{c} Scattering PP A2B2 \\ \texttt{incoming:2} \end{tabular}};

\draw [arrow] (netrada1) -- (scatppa1b1);
\draw [arrow] (netradb1) -- (scatppa1b1);
\draw [arrow] (netrada2) -- (scatppa2b2);
\draw [arrow] (netradb2) -- (scatppa2b2);

\end{tikzpicture}
```

## Wavefront pattern

``` tikz
\definecolor{cosmiclatte}{HTML}{FFF8E7}
\begin{tikzpicture}[background rectangle/.style={fill=cosmiclatte}, show background rectangle]
\tikzstyle{queue} = [rectangle, rounded corners, minimum width=3cm, minimum height=1cm,text centered, draw=black, fill=yellow!70]
\tikzstyle{run} = [rectangle, rounded corners, minimum width=3cm, minimum height=1cm,text centered, draw=black, fill=red!70]
\tikzstyle{finished} = [rectangle, rounded corners, minimum width=3cm, minimum height=1cm,text centered, draw=black, fill=green!70]
\tikzstyle{arrow} = [thick,->,>=stealth, draw=black]

\node (scata) [finished] {Scattering A};
\node (scatb) [run, right of=scata, xshift=3cm] {Scattering B};
\node (fresnel1) [run, right of=scatb, xshift=3cm] {Fresnel 1};
\node (fresnel2) [run, right of=fresnel1, xshift=3cm] {Fresnel 2};

\node (netrada1) [queue, below of=scata, yshift=-1.5cm] {\begin{tabular}{c} Net Rad A1 \\ \texttt{incoming:1} \end{tabular}};
\node (netrada2) [queue, below of=scatb, yshift=-1.5cm] {\begin{tabular}{c} Net Rad A2 \\ \texttt{incoming:1} \end{tabular}};
\node (netradb1) [queue, below of=fresnel1, yshift=-1.5cm] {\begin{tabular}{c} Net Rad B1 \\ \texttt{incoming:2} \end{tabular}};
\node (netradb2) [queue, below of=fresnel2, yshift=-1.5cm] {\begin{tabular}{c} Net Rad B2 \\ \texttt{incoming:2} \end{tabular}};

\draw [arrow] (scata) -- (netrada1);
\draw [arrow] (scata) -- (netrada2);
\draw [arrow] (scatb) -- (netradb1);
\draw [arrow] (scatb) -- (netradb2);
\draw [arrow] (fresnel1) -- (netrada1);
\draw [arrow] (fresnel1) -- (netradb1);
\draw [arrow] (fresnel2) -- (netrada2);
\draw [arrow] (fresnel2) -- (netradb2);

\node (scatppa1b1) [queue, below of=netrada1, yshift=-1.5cm, xshift=2cm] {\begin{tabular}{c} Scattering PP A1B1 \\ \texttt{incoming:2} \end{tabular}};
\node (scatppa2b2) [queue, below of=netradb1, yshift=-1.5cm, xshift=2cm] {\begin{tabular}{c} Scattering PP A2B2 \\ \texttt{incoming:2} \end{tabular}};

\draw [arrow] (netrada1) -- (scatppa1b1);
\draw [arrow] (netradb1) -- (scatppa1b1);
\draw [arrow] (netrada2) -- (scatppa2b2);
\draw [arrow] (netradb2) -- (scatppa2b2);

\end{tikzpicture}
```

## Wavefront pattern

``` tikz
\definecolor{cosmiclatte}{HTML}{FFF8E7}
\begin{tikzpicture}[background rectangle/.style={fill=cosmiclatte}, show background rectangle]
\tikzstyle{queue} = [rectangle, rounded corners, minimum width=3cm, minimum height=1cm,text centered, draw=black, fill=yellow!70]
\tikzstyle{run} = [rectangle, rounded corners, minimum width=3cm, minimum height=1cm,text centered, draw=black, fill=red!70]
\tikzstyle{finished} = [rectangle, rounded corners, minimum width=3cm, minimum height=1cm,text centered, draw=black, fill=green!70]
\tikzstyle{arrow} = [thick,->,>=stealth, draw=black]

\node (scata) [finished] {Scattering A};
\node (scatb) [run, right of=scata, xshift=3cm] {Scattering B};
\node (fresnel1) [run, right of=scatb, xshift=3cm] {Fresnel 1};
\node (fresnel2) [finished, right of=fresnel1, xshift=3cm] {Fresnel 2};

\node (netrada1) [queue, below of=scata, yshift=-1.5cm] {\begin{tabular}{c} Net Rad A1 \\ \texttt{incoming:1} \end{tabular}};
\node (netrada2) [run, below of=scatb, yshift=-1.5cm] {\begin{tabular}{c} Net Rad A2 \\ \texttt{incoming:0} \end{tabular}};
\node (netradb1) [queue, below of=fresnel1, yshift=-1.5cm] {\begin{tabular}{c} Net Rad B1 \\ \texttt{incoming:2} \end{tabular}};
\node (netradb2) [queue, below of=fresnel2, yshift=-1.5cm] {\begin{tabular}{c} Net Rad B2 \\ \texttt{incoming:2} \end{tabular}};

\draw [arrow] (scata) -- (netrada1);
\draw [arrow] (scata) -- (netrada2);
\draw [arrow] (scatb) -- (netradb1);
\draw [arrow] (scatb) -- (netradb2);
\draw [arrow] (fresnel1) -- (netrada1);
\draw [arrow] (fresnel1) -- (netradb1);
\draw [arrow] (fresnel2) -- (netrada2);
\draw [arrow] (fresnel2) -- (netradb2);

\node (scatppa1b1) [queue, below of=netrada1, yshift=-1.5cm, xshift=2cm] {\begin{tabular}{c} Scattering PP A1B1 \\ \texttt{incoming:2} \end{tabular}};
\node (scatppa2b2) [queue, below of=netradb1, yshift=-1.5cm, xshift=2cm] {\begin{tabular}{c} Scattering PP A2B2 \\ \texttt{incoming:2} \end{tabular}};

\draw [arrow] (netrada1) -- (scatppa1b1);
\draw [arrow] (netradb1) -- (scatppa1b1);
\draw [arrow] (netrada2) -- (scatppa2b2);
\draw [arrow] (netradb2) -- (scatppa2b2);

\end{tikzpicture}
```

## Wavefront pattern

``` tikz
\definecolor{cosmiclatte}{HTML}{FFF8E7}
\begin{tikzpicture}[background rectangle/.style={fill=cosmiclatte}, show background rectangle]
\tikzstyle{queue} = [rectangle, rounded corners, minimum width=3cm, minimum height=1cm,text centered, draw=black, fill=yellow!70]
\tikzstyle{run} = [rectangle, rounded corners, minimum width=3cm, minimum height=1cm,text centered, draw=black, fill=red!70]
\tikzstyle{finished} = [rectangle, rounded corners, minimum width=3cm, minimum height=1cm,text centered, draw=black, fill=green!70]
\tikzstyle{arrow} = [thick,->,>=stealth, draw=black]

\node (scata) [finished] {Scattering A};
\node (scatb) [finished, right of=scata, xshift=3cm] {Scattering B};
\node (fresnel1) [finished, right of=scatb, xshift=3cm] {Fresnel 1};
\node (fresnel2) [finished, right of=fresnel1, xshift=3cm] {Fresnel 2};

\node (netrada1) [run, below of=scata, yshift=-1.5cm] {\begin{tabular}{c} Net Rad A1 \\ \texttt{incoming:0} \end{tabular}};
\node (netrada2) [finished, below of=scatb, yshift=-1.5cm] {\begin{tabular}{c} Net Rad A2 \\ \texttt{incoming:0} \end{tabular}};
\node (netradb1) [run, below of=fresnel1, yshift=-1.5cm] {\begin{tabular}{c} Net Rad B1 \\ \texttt{incoming:0} \end{tabular}};
\node (netradb2) [run, below of=fresnel2, yshift=-1.5cm] {\begin{tabular}{c} Net Rad B2 \\ \texttt{incoming:0} \end{tabular}};

\draw [arrow] (scata) -- (netrada1);
\draw [arrow] (scata) -- (netrada2);
\draw [arrow] (scatb) -- (netradb1);
\draw [arrow] (scatb) -- (netradb2);
\draw [arrow] (fresnel1) -- (netrada1);
\draw [arrow] (fresnel1) -- (netradb1);
\draw [arrow] (fresnel2) -- (netrada2);
\draw [arrow] (fresnel2) -- (netradb2);

\node (scatppa1b1) [queue, below of=netrada1, yshift=-1.5cm, xshift=2cm] {\begin{tabular}{c} Scattering PP A1B1 \\ \texttt{incoming:2} \end{tabular}};
\node (scatppa2b2) [queue, below of=netradb1, yshift=-1.5cm, xshift=2cm] {\begin{tabular}{c} Scattering PP A2B2 \\ \texttt{incoming:1} \end{tabular}};

\draw [arrow] (netrada1) -- (scatppa1b1);
\draw [arrow] (netradb1) -- (scatppa1b1);
\draw [arrow] (netrada2) -- (scatppa2b2);
\draw [arrow] (netradb2) -- (scatppa2b2);

\end{tikzpicture}
```

## Wavefront pattern

``` tikz
\definecolor{cosmiclatte}{HTML}{FFF8E7}
\begin{tikzpicture}[background rectangle/.style={fill=cosmiclatte}, show background rectangle]
\tikzstyle{queue} = [rectangle, rounded corners, minimum width=3cm, minimum height=1cm,text centered, draw=black, fill=yellow!70]
\tikzstyle{run} = [rectangle, rounded corners, minimum width=3cm, minimum height=1cm,text centered, draw=black, fill=red!70]
\tikzstyle{finished} = [rectangle, rounded corners, minimum width=3cm, minimum height=1cm,text centered, draw=black, fill=green!70]
\tikzstyle{arrow} = [thick,->,>=stealth, draw=black]

\node (scata) [finished] {Scattering A};
\node (scatb) [finished, right of=scata, xshift=3cm] {Scattering B};
\node (fresnel1) [finished, right of=scatb, xshift=3cm] {Fresnel 1};
\node (fresnel2) [finished, right of=fresnel1, xshift=3cm] {Fresnel 2};

\node (netrada1) [finished, below of=scata, yshift=-1.5cm] {\begin{tabular}{c} Net Rad A1 \\ \texttt{incoming:0} \end{tabular}};
\node (netrada2) [finished, below of=scatb, yshift=-1.5cm] {\begin{tabular}{c} Net Rad A2 \\ \texttt{incoming:0} \end{tabular}};
\node (netradb1) [finished, below of=fresnel1, yshift=-1.5cm] {\begin{tabular}{c} Net Rad B1 \\ \texttt{incoming:0} \end{tabular}};
\node (netradb2) [finished, below of=fresnel2, yshift=-1.5cm] {\begin{tabular}{c} Net Rad B2 \\ \texttt{incoming:0} \end{tabular}};

\draw [arrow] (scata) -- (netrada1);
\draw [arrow] (scata) -- (netrada2);
\draw [arrow] (scatb) -- (netradb1);
\draw [arrow] (scatb) -- (netradb2);
\draw [arrow] (fresnel1) -- (netrada1);
\draw [arrow] (fresnel1) -- (netradb1);
\draw [arrow] (fresnel2) -- (netrada2);
\draw [arrow] (fresnel2) -- (netradb2);

\node (scatppa1b1) [run, below of=netrada1, yshift=-1.5cm, xshift=2cm] {\begin{tabular}{c} Scattering PP A1B1 \\ \texttt{incoming:0} \end{tabular}};
\node (scatppa2b2) [run, below of=netradb1, yshift=-1.5cm, xshift=2cm] {\begin{tabular}{c} Scattering PP A2B2 \\ \texttt{incoming:0} \end{tabular}};

\draw [arrow] (netrada1) -- (scatppa1b1);
\draw [arrow] (netradb1) -- (scatppa1b1);
\draw [arrow] (netrada2) -- (scatppa2b2);
\draw [arrow] (netradb2) -- (scatppa2b2);

\end{tikzpicture}
```

## Wavefront pattern

``` tikz
\definecolor{cosmiclatte}{HTML}{FFF8E7}
\begin{tikzpicture}[background rectangle/.style={fill=cosmiclatte}, show background rectangle]
\tikzstyle{queue} = [rectangle, rounded corners, minimum width=3cm, minimum height=1cm,text centered, draw=black, fill=yellow!70]
\tikzstyle{run} = [rectangle, rounded corners, minimum width=3cm, minimum height=1cm,text centered, draw=black, fill=red!70]
\tikzstyle{finished} = [rectangle, rounded corners, minimum width=3cm, minimum height=1cm,text centered, draw=black, fill=green!70]
\tikzstyle{arrow} = [thick,->,>=stealth, draw=black]

\node (scata) [finished] {Scattering A};
\node (scatb) [finished, right of=scata, xshift=3cm] {Scattering B};
\node (fresnel1) [finished, right of=scatb, xshift=3cm] {Fresnel 1};
\node (fresnel2) [finished, right of=fresnel1, xshift=3cm] {Fresnel 2};

\node (netrada1) [finished, below of=scata, yshift=-1.5cm] {\begin{tabular}{c} Net Rad A1 \\ \texttt{incoming:0} \end{tabular}};
\node (netrada2) [finished, below of=scatb, yshift=-1.5cm] {\begin{tabular}{c} Net Rad A2 \\ \texttt{incoming:0} \end{tabular}};
\node (netradb1) [finished, below of=fresnel1, yshift=-1.5cm] {\begin{tabular}{c} Net Rad B1 \\ \texttt{incoming:0} \end{tabular}};
\node (netradb2) [finished, below of=fresnel2, yshift=-1.5cm] {\begin{tabular}{c} Net Rad B2 \\ \texttt{incoming:0} \end{tabular}};

\draw [arrow] (scata) -- (netrada1);
\draw [arrow] (scata) -- (netrada2);
\draw [arrow] (scatb) -- (netradb1);
\draw [arrow] (scatb) -- (netradb2);
\draw [arrow] (fresnel1) -- (netrada1);
\draw [arrow] (fresnel1) -- (netradb1);
\draw [arrow] (fresnel2) -- (netrada2);
\draw [arrow] (fresnel2) -- (netradb2);

\node (scatppa1b1) [finished, below of=netrada1, yshift=-1.5cm, xshift=2cm] {\begin{tabular}{c} Scattering PP A1B1 \\ \texttt{incoming:0} \end{tabular}};
\node (scatppa2b2) [finished, below of=netradb1, yshift=-1.5cm, xshift=2cm] {\begin{tabular}{c} Scattering PP A2B2 \\ \texttt{incoming:0} \end{tabular}};

\draw [arrow] (netrada1) -- (scatppa1b1);
\draw [arrow] (netradb1) -- (scatppa1b1);
\draw [arrow] (netrada2) -- (scatppa2b2);
\draw [arrow] (netradb2) -- (scatppa2b2);

\end{tikzpicture}
```

Lock-free: a finished node checks if it can start its downstream nodes.

## Task indices

:::: {.columns}

::: {.column width="50%"}
``` tikz
\definecolor{cosmiclatte}{HTML}{FFF8E7}
\begin{tikzpicture}[background rectangle/.style={fill=cosmiclatte}, show background rectangle]
\tikzstyle{queue} = [rectangle, minimum width=1.5cm, minimum height=1cm,text centered, draw=black, fill=yellow]

\node (n000) [queue] {$(0,0,0)$};
\node (n001) [queue, right=0mm of n000] {$(0,0,1)$};
\node (n002) [queue, right=0mm of n001] {$(0,0,2)$};
\node (n003) [queue, right=0mm of n002] {$(0,0,3)$};

\node (n010) [queue, below=0mm of n000] {$(0,1,0)$};
\node (n011) [queue, right=0mm of n010] {$(0,1,1)$};
\node (n012) [queue, right=0mm of n011] {$(0,1,2)$};
\node (n013) [queue, right=0mm of n012] {$(0,1,3)$};

\node (n020) [queue, below=0mm of n010] {$(0,2,0)$};
\node (n021) [queue, right=0mm of n020] {$(0,2,1)$};
\node (n022) [queue, right=0mm of n021] {$(0,2,2)$};
\node (n023) [queue, right=0mm of n022] {$(0,2,3)$};

\node (n100) [queue, below=of n020] {$(1,0,0)$};
\node (n101) [queue, right=0mm of n100] {$(1,0,1)$};
\node (n102) [queue, right=0mm of n101] {$(1,0,2)$};
\node (n103) [queue, right=0mm of n102] {$(1,0,3)$};

\node (n110) [queue, below=0mm of n100] {$(1,1,0)$};
\node (n111) [queue, right=0mm of n110] {$(1,1,1)$};
\node (n112) [queue, right=0mm of n111] {$(1,1,2)$};
\node (n113) [queue, right=0mm of n112] {$(1,1,3)$};

\node (n120) [queue, below=0mm of n110] {$(1,2,0)$};
\node (n121) [queue, right=0mm of n120] {$(1,2,1)$};
\node (n122) [queue, right=0mm of n121] {$(1,2,2)$};
\node (n123) [queue, right=0mm of n122] {$(1,2,3)$};
\end{tikzpicture}
```
:::

::: {.column width="50%"}
$$
\begin{aligned}
i_a &= \lfloor k / (n_b  n_c) \rfloor \\
j_a &= k \bmod (n_b  n_c) \\
i_b &= \lfloor j_a / n_c       \rfloor\\
j_b &= j_a \bmod n_c \\
i_c &= j_b / 1
\end{aligned}
$$
:::

::::


``` tikz
\definecolor{cosmiclatte}{HTML}{FFF8E7}
\begin{tikzpicture}[background rectangle/.style={fill=cosmiclatte}, show background rectangle]
\tikzstyle{task0} = [rectangle, minimum width=1.5cm, minimum height=1cm,text centered, draw=black, fill=yellow]
\tikzstyle{task1} = [rectangle, minimum width=1.5cm, minimum height=1cm,text centered, draw=black, fill=blue!50]

\node (n000) [task0] {$(0,0,0)$};
\node (n001) [task0, right=0mm of n000] {$(\ldots)$};
\node (n002) [task0, right=0mm of n001] {$(0,0,3)$};
\node (n003) [task0, right=0mm of n002] {$(0,1,0)$};
\node (n004) [task0, right=0mm of n003] {$(\ldots)$};
\node (n005) [task0, right=0mm of n004] {$(0,1,3)$};
\node (n006) [task0, right=0mm of n005] {$(1,1,0)$};
\node (n007) [task0, right=0mm of n006] {$(\ldots)$};
\node (n008) [task0, right=0mm of n007] {$(1,1,3)$};
\node (p000) [task1, right=0mm of n008] {$(0,0,0)$};
\node (p001) [task1, right=0mm of p000] {$(\ldots)$};
\node (p002) [task1, right=0mm of p001] {$(0,0,3)$};
\node (p003) [task1, right=0mm of p002] {$(0,1,0)$};
\node (p004) [task1, right=0mm of p003] {$(\ldots)$};
\node (p005) [task1, right=0mm of p004] {$(0,1,3)$};
\node (p006) [task1, right=0mm of p005] {$(1,1,0)$};
\node (p007) [task1, right=0mm of p006] {$(\ldots)$};
\node (p008) [task1, right=0mm of p007] {$(1,1,3)$};
\end{tikzpicture}
```

Task vector: contiguous "row major" layout with index $(\mathtt{taskId}, i_0, \ldots, i_n)$.

## Graph structure - Adjacency matrix
:::: {.columns}

::: {.column width="50%"}
``` tikz
\definecolor{cosmiclatte}{HTML}{FFF8E7}
\begin{tikzpicture}[background rectangle/.style={fill=cosmiclatte}, show background rectangle]
\tikzstyle{scat} = [rectangle, rounded corners, minimum width=3cm, minimum height=1cm,text centered, draw=black, fill=yellow!50]
\tikzstyle{fresnel} = [rectangle, rounded corners, minimum width=3cm, minimum height=1cm,text centered, draw=black, fill=red!50]
\tikzstyle{nr} = [rectangle, rounded corners, minimum width=3cm, minimum height=1cm,text centered, draw=black, fill=green!50]
\tikzstyle{scatpp} = [rectangle, rounded corners, minimum width=3cm, minimum height=1cm,text centered, draw=black, fill=blue!50]
\tikzstyle{arrow} = [thick,->,>=stealth, draw=black]

\node (scata) [scat] {Scattering A};
\node (scatb) [scat, right of=scata, xshift=3cm] {Scattering B};
\node (fresnel1) [fresnel, right of=scatb, xshift=3cm] {Fresnel 1};
\node (fresnel2) [fresnel, right of=fresnel1, xshift=3cm] {Fresnel 2};

\node (netrada1) [nr, below of=scata, yshift=-1.5cm] {Net Rad A1};
\node (netrada2) [nr, below of=scatb, yshift=-1.5cm] {Net Rad A2};
\node (netradb1) [nr, below of=fresnel1, yshift=-1.5cm] {Net Rad B1};
\node (netradb2) [nr, below of=fresnel2, yshift=-1.5cm] {Net Rad B2};

\draw [arrow] (scata) -- (netrada1);
\draw [arrow] (scata) -- (netrada2);
\draw [arrow] (scatb) -- (netradb1);
\draw [arrow] (scatb) -- (netradb2);
\draw [arrow] (fresnel1) -- (netrada1);
\draw [arrow] (fresnel1) -- (netradb1);
\draw [arrow] (fresnel2) -- (netrada2);
\draw [arrow] (fresnel2) -- (netradb2);

\node (scatppa1b1) [scatpp, below of=netrada1, yshift=-1.5cm, xshift=2cm] {\begin{tabular}{c} Scattering PP A1B1 \\ \texttt{incoming:2} \end{tabular}};
\node (scatppa2b2) [scatpp, below of=netradb1, yshift=-1.5cm, xshift=2cm] {\begin{tabular}{c} Scattering PP A2B2 \\ \texttt{incoming:2} \end{tabular}};

\draw [arrow] (netrada1) -- (scatppa1b1);
\draw [arrow] (netradb1) -- (scatppa1b1);
\draw [arrow] (netrada2) -- (scatppa2b2);
\draw [arrow] (netradb2) -- (scatppa2b2);

\end{tikzpicture}
```
:::

::: {.column width="50%" style="font-size: 50%;"}
$$
\begin{array}{cccccccc}
0 & 0 & 0 & 0 & 1 & 1 & 0 & 0 & 0 & 0\\
0 & 0 & 0 & 0 & 0 & 0 & 1 & 1 & 0 & 0\\
0 & 0 & 0 & 0 & 1 & 0 & 1 & 0 & 0 & 0\\
0 & 0 & 0 & 0 & 0 & 1 & 0 & 1 & 0 & 0\\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 & 0\\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1\\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 & 0\\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1\\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\
\end{array}
$$
:::
::::

``` tikz
\definecolor{cosmiclatte}{HTML}{FFF8E7}
\begin{tikzpicture}[background rectangle/.style={fill=cosmiclatte}, show background rectangle]
\tikzstyle{scat} = [rectangle, minimum width=3cm, minimum height=1cm,text centered, draw=black, fill=yellow!50]
\tikzstyle{fresnel} = [rectangle, minimum width=3cm, minimum height=1cm,text centered, draw=black, fill=red!50]
\tikzstyle{nr} = [rectangle, minimum width=3cm, minimum height=1cm,text centered, draw=black, fill=green!50]
\tikzstyle{scatpp} = [rectangle, minimum width=3cm, minimum height=1cm,text centered, draw=black, fill=blue!50]

% indices are (A/B, 1/2)
\node (n000) [scat] {SA};
\node (n001) [scat, right=0mm of n000] {SB};
\node (n002) [fresnel, right=0mm of n001] {F1};
\node (n003) [fresnel, right=0mm of n002] {F2};
\node (n004) [nr, right=0mm of n003] {NRA1};
\node (n005) [nr, right=0mm of n004] {NRA2};
\node (n006) [nr, right=0mm of n005] {NRB1};
\node (n007) [nr, right=0mm of n006] {NRB2};
\node (n008) [scatpp, right=0mm of n007] {SPPA1B1};
\node (p000) [scatpp, right=0mm of n008] {SPPA2B2};
\end{tikzpicture}
```

Matrix is sparse.


## Graph structure - Forward/Backward star
:::: {.columns}

::: {.column width="50%" style="font-size: 50%;"}
$$
\begin{array}{cccccccc}
0 & 0 & 0 & 0 & 1 & 1 & 0 & 0 & 0 & 0\\
0 & 0 & 0 & 0 & 0 & 0 & 1 & 1 & 0 & 0\\
0 & 0 & 0 & 0 & 1 & 0 & 1 & 0 & 0 & 0\\
0 & 0 & 0 & 0 & 0 & 1 & 0 & 1 & 0 & 0\\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 & 0\\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1\\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 & 0\\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1\\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\
\end{array}
$$
:::

::: {.column width="50%"}
``` tikz
\definecolor{cosmiclatte}{HTML}{FFF8E7}
\begin{tikzpicture}[background rectangle/.style={fill=cosmiclatte}, show background rectangle]
\tikzstyle{scat} = [rectangle, minimum width=1cm, minimum height=1cm,text centered, draw=black, fill=yellow!50]
\tikzstyle{fresnel} = [rectangle, minimum width=1cm, minimum height=1cm,text centered, draw=black, fill=red!50]
\tikzstyle{nr} = [rectangle, minimum width=1cm, minimum height=1cm,text centered, draw=black, fill=green!50]
\tikzstyle{scatpp} = [rectangle, minimum width=1cm, minimum height=1cm,text centered, draw=black, fill=blue!50]
\tikzstyle{arrow} = [thick,->,>=stealth, draw=black]

% indices are (A/B, 1/2)
\node (z000) [scat] {1};
\node (z001) [scat, right=0mm of z000] {1};
\node (z002) [scat, right=0mm of z001] {1};
\node (z003) [scat, right=0mm of z002] {1};
\node (z004) [fresnel, right=0mm of z003] {1};
\node (z005) [fresnel, right=0mm of z004] {1};
\node (z006) [fresnel, right=0mm of z005] {1};
\node (z007) [fresnel, right=0mm of z006] {1};
\node (z008) [nr, right=0mm of z007] {1};
\node (z009) [nr, right=0mm of z008] {1};
\node (z010) [nr, right=0mm of z009] {1};
\node (z011) [nr, right=0mm of z010] {1};

\node (n000) [scat, below=of z000] {4};
\node (n001) [scat, right=0mm of n000] {5};
\node (n002) [scat, right=0mm of n001] {6};
\node (n003) [scat, right=0mm of n002] {7};
\node (n004) [fresnel, right=0mm of n003] {4};
\node (n005) [fresnel, right=0mm of n004] {6};
\node (n006) [fresnel, right=0mm of n005] {5};
\node (n007) [fresnel, right=0mm of n006] {7};
\node (n008) [nr, right=0mm of n007] {8};
\node (n009) [nr, right=0mm of n008] {9};
\node (n010) [nr, right=0mm of n009] {8};
\node (n011) [nr, right=0mm of n010] {9};

\node (p000) [scat, below=of n000] {2};
\node (p001) [scat, right=0mm of p000] {4};
\node (p002) [scat, right=0mm of p001] {6};
\node (p003) [scat, right=0mm of p002] {8};
\node (p004) [scat, right=0mm of p003] {9};
\node (p005) [scat, right=0mm of p004] {10};
\node (p006) [scat, right=0mm of p005] {11};
\node (p007) [scat, right=0mm of p006] {12};

\draw [arrow] (p000.north) -- (n002.south west);
\draw [arrow] (p001.north) -- (n004.south west);
\draw [arrow] (p002.north) -- (n006.south west);
\draw [arrow] (p003.north) -- (n008.south west);
\draw [arrow] (p004.north) -- (n009.south west);
\draw [arrow] (p005.north) -- (n010.south west);
\draw [arrow] (p006.north) -- (n011.south west);
\draw [arrow] (p007.north) -- (n011.south east);
\end{tikzpicture}
```
:::
::::

Condensed-Storage-Rows (CSR) format $\Rightarrow$ Forward star. Allows to find outgoing nodes. Similarly, CSC $\Rightarrow$ backward star.

## `AbstractTask`

* Corresponds to node in abstract graph
* knows dependencies (incoming edges)
* can tell which sweep parameters are relevant
* contains "payload" as functor
* fairly low level

## `TaskTraits`

```cpp
template<> struct TaskTraits<TaskId::Emission>
{
   static constexpr std::array<TaskId, 2> dependencies{TaskId::Collect_NetRadiationPassiveOptics,
                                                       TaskId::Collect_Emission};

   using ResultType = Optics::TaskEmissionCoupling;
   using ParameterType = Optics::TaskEmissionParameters;
   using TaskType = Optics::TaskEmission;

   // ...
}
```

## `GenericTaskParameters`
 
```cpp
class TaskNetRadiationParameters
  : public GenericTaskParameters<
            GenericTaskParameterId::LIGHT_HANDLING,
            GenericTaskParameterId::ABSORPTION_EMISSION_MODE>
  {
```

Combines sweepable parameters (given as template arguments)

```cpp
std::unique_ptr<AbstractTaskResult> TaskNetRadiation::run(
const TaskNetRadiationParameters &pars, ...) {
  bool absorptionEmissionMode =
  pars.get<GenericTaskParameterId::ABSORPTION_EMISSION_MODE>();
```


## `GenericTaskParameters`

```cpp
template<> struct GenericTaskParameterTraits<GenericTaskParameterId::ABSORPTION_EMISSION_MODE>
{
   // true means emission ;)
   using ValueType = bool;
};
template<>
GenericTaskParameterTraits<GenericTaskParameterId::ABSORPTION_EMISSION_MODE>::ValueType
create<GenericTaskParameterId::ABSORPTION_EMISSION_MODE>(SimulationParameter const& simp)
{
   return simp.getMLOP().getEmission();
}
template<>
bool isParameterRelevant<GenericTaskParameterId::ABSORPTION_EMISSION_MODE>(ParameterIdentifier const& pid,
                                                                           SimulationParameter const&)
{
   const ParameterIdentifier::mlop_idtype mlopId = pid.getMLOPID();
   switch (mlopId)
   {
      case ParameterIdentifier::P_EMISSION: return true;
      default: return false;
   }
};
template<>
  void setValue<GenericTaskParameterId::ABSORPTION_EMISSION_MODE>(
     typename GenericTaskParameterTraits<GenericTaskParameterId::ABSORPTION_EMISSION_MODE>::ValueType& val,
     ParameterIdentifier const& pid, double value, int)
  {
     const ParameterIdentifier::mlop_idtype mlopId = pid.getMLOPID();
     switch (mlopId)
     {
        case ParameterIdentifier::ParameterIdentifier::P_EMISSION: val = (value == 0 ? false : true);
        default:
        {
        }
     }
  };
```

## `GenericTaskParameters`

```cpp
template<GenericTaskParameterId... ids> class GenericTaskParameters
{

// ...

static constexpr bool isParameterRelevant(ParameterIdentifier const& pid,
   SimulationParameter const& simp)
{
   return
     (GenericTaskParameterSetters::isParameterRelevant<ids>(pid, simp) || ...);
};

void setValue(ParameterIdentifier const& pid, double value, int index)
{
   (GenericTaskParameterSetters::setValue<ids>(get<ids>(), pid, value, index), ...);
};
```

## Generic Task
``` tikz
\scalebox{1.5}{
\definecolor{cosmiclatte}{HTML}{FFF8E7}
\begin{tikzpicture}[background rectangle/.style={fill=cosmiclatte}, show background rectangle]
\tikzstyle{simple} = [rectangle, rounded corners, minimum width=3cm, minimum height=1cm,text centered, draw=black, fill=yellow!70]
\tikzstyle{arrow} = [thick,->,>=stealth, draw=black]
\node (Sweeper) [simple] {\texttt{Sweeper}};
\node (AbstractTask) [simple, right= of Sweeper, xshift=2.5cm] {\texttt{AbstractTask}};
\node (GenericTask) [simple, below= of AbstractTask] {\texttt{GenericTask<taskId>::run}};
\node (GenericTaskPar) [simple, below = of GenericTask, xshift = -2.5cm] {\texttt{GenericTaskParameter<taskId>::set}};
\node (Task) [simple, below = of GenericTask, xshift = 2.5cm, yshift=-2.5cm] {\texttt{TaskTraits<taskId>::TaskType::run}};

\draw [arrow] (Sweeper) edge["creates"] (AbstractTask);
\draw [arrow] (AbstractTask) edge["runs"] (GenericTask);
\draw [arrow] (GenericTask) edge["calls"] (GenericTaskPar);
\draw [arrow] (GenericTaskPar) edge["input"] (Task);
\draw [arrow] (GenericTask) edge["calls"] (Task);
\end{tikzpicture}
}
```

## Task Run Method

```cpp
std::unique_ptr<AbstractTaskResult>
TaskEmission::run(TaskEmissionParameters const&,
                  TaskCollectEmissionResultsCoupling const& emissionCoupling,
                  TaskCollectNetRadiationPassiveOpticsResultsCoupling const& nrPoCoupling)
{
// ..
}
```

`GenericTask::run` takes parameters and dependencies from `TaskTraits` and calls the run method with signature

```cpp
TaskTraits<taskId>::TaskType::run(
      TaskTraits<taskId>::ParameterType const &par,
      TaskTraits<TaskTraits<taskId>::dependencies[N-1]>::ResultType const &dep1,
      TaskTraits<TaskTraits<taskId>::dependencies[N-2]>::ResultType const &dep2,
      // ...
      TaskTraits<TaskTraits<taskId>::dependencies[0]>::ResultType const &dep2)
```

# How to define abstract graph?

* "scenario"-wise (e.g. pure DD, DD+EM, etc..)
* node-wise (`TaskDriftDiffusion` is needed if DD is active)
* result-wise (we need DD result and all inputs)

# Under construction

* Memory consumption for large sweeps
* `AbstractTask` is a mess
* `AbstractTaskResults` has a huge `std::variant`
* Naming
